name:                hs-web
version:             0.1.0.0
github:              "githubuser/hs-web"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hs-web#readme>

dependencies:
- base >= 4.7 && < 5
- servant
- servant-server
- aeson
- warp
- lucid
- lucid-htmx
- servant-htmx
- servant-lucid
- text
- http-types
- dotenv
- transformers
- http-client
- http-conduit
- bytestring
- postgresql-simple
- opaleye
- product-profunctors
- http-api-data
- cookie

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: 
    - src

executables:
  hs-web-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-web

tests:
  hs-web-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-web
